### ISSUE TITLE
javascript error when electron has been left running and try to right-click

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#88] opened 2016-11-18 13:39 UTC
In the latest version of master branch. If you leave Electron running, sleep your computer (ie. carry it home) when electron reloads, it is throwing an error when you right click on a anything. If you quit Electron and relaunch it, everything is fine again.

Screen snapshots attached.

---
Please include: 
- `macOS Sierra`
- `Leave zulip-electron running, sleep computer, right click misspelled word`

![screen shot 2016-11-18 at 9 23 09 am](https://cloud.githubusercontent.com/assets/963514/20431861/b4e95b1c-ad72-11e6-86a9-74c999f04750.png)
![screen shot 2016-11-18 at 9 23 20 am](https://cloud.githubusercontent.com/assets/963514/20431864/b9fd04e6-ad72-11e6-9854-abcedce6c3c9.png)

**Comment by timabbott** [comment] 2016-12-01 17:51
Interesting, I think I saw the same error on Linux yesterday where I closed the Electron window and then was using ctrl-R to search in my terminal history - I couldn't quite get a reproduction though.  

Definitely seems like this is a priority issue.

**Comment by akashnimare** [comment] 2016-12-13 21:42
@GervaisdeM the error you are getting is because of the spellchecker event. I have pushed a fix, let me know if it works 😅 

@timabbott I have seen that error once but I'm not able to reproduce it now 😄 
Maybe it's caused by the local keyboard shortcuts i.e. [this](https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L173). These shortcuts are registered once the app is open. Probably I need to unregister them once the app is closed so that they don't get conflicted with other apps. Let me know if you get a reproduction.

**Comment by timabbott** [comment] 2016-12-13 22:28
I can't reproduce it directly but it happens a few times a day when I have the app open, so I can determine whether something fixed it.  It would be really good to make sure we fix this in a way that it's not going to regress, since this is a pretty bad failure mode.

**Comment by akashnimare** [comment] 2016-12-14 20:34
@timabbott I have pushed a fix in https://github.com/zulip/zulip-electron/commit/61dfcfc3b110a6cc12a11a1d1ccf471728551d68. Let me know if you get this error again.

**Comment by timabbott** [comment] 2016-12-14 20:38
OK I'll run the latest version for the next couple days and post here if I see the issue again.

**Comment by timabbott** [comment] 2016-12-15 17:30
I had it running all day and haven't seen this, so I think it is indeed fixed.

**Closed by timabbott** 2016-12-15 17:30 UTC
Labels: bug
