### ISSUE TITLE
"(more topics)" link does not display any topic

### ISSUE THREAD

**Issue by jjst** [zulip/zulip-electron#21] opened 2016-07-26 15:10 UTC
The "(more topics)" link displayed below the most recent topics of a stream in the stream view on the left doesn't work: clicking on it brings you to an empty list of topics.

**Comment by akashnimare** [comment] 2016-07-26 20:46
I thinks it's working as expected.
<img src="http://im2.ezgif.com/tmp/ezgif-3241674614.gif">

**Comment by akashnimare** [comment] 2016-08-04 17:00
Closing until more info given.

**Closed by akashnimare** 2016-08-04 17:00 UTC
Labels: more-information-needed

**Comment by jjst** [comment] 2016-08-04 18:51
Yeah, it's working in some cases and not in others -- maybe I was mistaken and there weren't anymore topics. I'll reopen when/if I find more info.

**Comment by akashnimare** [comment] 2016-08-04 18:57
Sometimes I get the same behaviour on web(browser) as well. I think this might be issue with Zulip  not the app.

**Comment by timabbott** [comment] 2016-08-04 18:58
A bug of this form is very likely to be a Zulip webapp bug that we should track in the zulip/zulip project; I don't see a mechanism for the desktop app to cause that.

**Comment by akashnimare** [comment] 2016-08-04 19:01
Yes, I think the problem with the Zulip webapp. Although I am not able to reproduce it. It occurs very rarely.
