### ISSUE TITLE
Add support for custom/self signed  certificate authority

### ISSUE THREAD

**Issue by timapril** [zulip/zulip-electron#25] opened 2016-07-27 20:20 UTC
zulip-electron returns the error of "Not valid url" when trying to access a zulip install that uses a CA chain that is not in the default trust store. One of the installs that I have uses a certificate that is not signed by a globally trusted CA. 

The current error that I am getting (when I modify main.js to log the response in the check url callback) is 

> Error: self signed certificate in certificate chain(…)

**Comment by mgrabow1** [comment] 2016-09-07 14:18
Also interested in this feature. My company has it's own CA and the top-level certificate is a self-signed one. That's probably why I keep getting "Not a valid Zulip server". Web and desktp versions are working fine.

**Comment by steele** [comment] 2016-09-11 14:21
I have the same issue - I used the following workaround, but note that it effective removes the security provided by TLS and so I strongly recommend that it should only be used if you are on a very trusted network.

> export NODE_TLS_REJECT_UNAUTHORIZED=0

(Use _set_ instead of _export_ on Windows)

Once logged in, I now appear to no longer require the environment variable be set when starting the application.

@akashnimare I can take a look at this issue if you want to assign it to me (if that is possible)

**Comment by akashnimare** [comment] 2016-09-11 22:11
@steele I'm not able to reproduce this issue yet. I'm setting up Zulip locally to see what's going on with self-signed ca. As for as I know to resolve this we need to import these certificates. To get better idea you can go through these threads -

https://github.com/electron/electron/issues/1956
https://github.com/electron/electron/issues/6222
https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

> I can take a look at this issue if you want to assign it to me (if that is possible)

Go ahead 🎅 .

**Comment by akashnimare** [comment] 2017-04-21 14:22
Moving this to #126

**Closed by akashnimare** 2017-04-21 14:22 UTC
Labels: help wanted, Priority: High, Type: Enhancement
