### ISSUE TITLE
Open context menu on touch events

### ISSUE THREAD

**Issue by antifuchs** [zulip/zulip-electron#98] opened 2017-01-03 09:35 UTC
I run Zulip electron on the mac, and have noticed recently that when I click links to external pages (not images), the electron app opens a chrome-less window that doesn't let me open the page in a browser.

Steps to reproduce:
1. Post the link `https://example.com` on a zulip instance
2. Click that link
=> A window inside zulip-electron pops up

Expected result: my browser should open a new tab.
Alternative result: The window should have a button to open the page in a browser, or show a URL.

I noticed that the electron app no longer shows a context menu when right-clicking on these links, which makes getting a copy-able URL from them even harder...

**Comment by akashnimare** [comment] 2017-01-03 09:48
@antifuchs thanks for opening this. It's https://github.com/zulip/zulip-electron/issues/11 again 😭 
I'll send a fix.

**Comment by akashnimare** [comment] 2017-01-03 10:03
@acrefoot which version of zulip-electron are you using? Could you please try it on latest master?

>I noticed that the electron app no longer shows a context menu when right-clicking on these links, which makes getting a copy-able URL from them even harder...

It's there in the latest release. See - 

![image](https://cloud.githubusercontent.com/assets/2263909/21604350/b7d1c7f4-d1c8-11e6-8cf1-509766d33c25.png)

**Comment by antifuchs** [comment] 2017-01-03 10:11
Oh dang, I wasn't on a release when repo'ing this: I reported against eac2b92cb671fba290ef4865bba4c03033edc077.

The latest HEAD (531973194c4e8c018079e8a068b25800232c997b) now does open links in a new browser tab, but I am not able to open the context menu: I only have a touchpad available, and neither two-finger-tapping (as configured system-wide) nor control-clicking opens a context menu for me.

**Comment by akashnimare** [comment] 2017-01-03 10:21
@antifuchs ohh, I haven't consider the touchpad case yet 😆  
I'll be adding this in next release.

**Comment by geeeeeeeeek** [comment] 2017-03-04 16:11
@antifuchs I cannot reproduce it on my Mac. Urls work well with tapping and control clicking. 

@akashnimare Has this been fixed, and shall we close it?

**Comment by akashnimare** [comment] 2017-03-06 09:54
@geeeeeeeeek let's just wait and see if @antifuchs could reproduce this again.

**Comment by timabbott** [comment] 2017-07-07 16:43
@antifuchs can you verify whether the latest Zulip electron works fine on your touchpad?  We're closing this issue for now, since we cannot reproduce.

**Closed by timabbott** 2017-07-07 16:43 UTC
Labels: help wanted, Priority: Medium, reply-needed, Type: Enhancement

**Comment by antifuchs** [comment] 2017-07-08 04:29
Thanks for the update - I just tested and two-finger-tap on the touchpad totally works now!
