### ISSUE TITLE
Private messages with many participants *breaks* UI

### ISSUE THREAD

**Issue by fedeisas** [zulip/zulip-electron#142] opened 2017-04-24 22:38 UTC
Hi there! I'm using Zulip 0.5.2 on OSX. Someone created two Private Messages with 20+ participants each and now I can't scroll to see the rest of my private messages.

I think the easiest solution is to trim the number of characters in the private messages.

**The red boxes are my private messages.**

![image](https://cloud.githubusercontent.com/assets/251675/25361569/f3cf10e4-291c-11e7-92e7-ca8c64764832.png)

**Comment by timabbott** [comment] 2017-04-24 23:15
This is a duplicate of https://github.com/zulip/zulip/issues/1991

**Closed by timabbott** 2017-04-24 23:15 UTC
